// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5q3agRlu7k0dIkBbJT3QlYOehM9C1CYo',
    appId: '1:133950710116:web:a777c4661ad8ecd9239a71',
    messagingSenderId: '133950710116',
    projectId: 'vehicleapp-5851f',
    authDomain: 'vehicleapp-5851f.firebaseapp.com',
    storageBucket: 'vehicleapp-5851f.firebasestorage.app',
    measurementId: 'G-RZZ3YC66LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gX---qesXUotLwfy-z3lFsPsHYJ8weA',
    appId: '1:133950710116:android:23b5d9ebd0d4147c239a71',
    messagingSenderId: '133950710116',
    projectId: 'vehicleapp-5851f',
    storageBucket: 'vehicleapp-5851f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmzcq5aaRQyUyhPQdZTgl1dRwf6ANDDtI',
    appId: '1:133950710116:ios:c2e7b57f39876629239a71',
    messagingSenderId: '133950710116',
    projectId: 'vehicleapp-5851f',
    storageBucket: 'vehicleapp-5851f.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmzcq5aaRQyUyhPQdZTgl1dRwf6ANDDtI',
    appId: '1:133950710116:ios:c2e7b57f39876629239a71',
    messagingSenderId: '133950710116',
    projectId: 'vehicleapp-5851f',
    storageBucket: 'vehicleapp-5851f.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5q3agRlu7k0dIkBbJT3QlYOehM9C1CYo',
    appId: '1:133950710116:web:eead4d631e9d512e239a71',
    messagingSenderId: '133950710116',
    projectId: 'vehicleapp-5851f',
    authDomain: 'vehicleapp-5851f.firebaseapp.com',
    storageBucket: 'vehicleapp-5851f.firebasestorage.app',
    measurementId: 'G-W7LHM3G3RR',
  );
}
